hmrc/for-frontend

app/config/wiring.scala, app/connectors/SubmissionConnector.scala, app/controllers/FORSubmissionController.scala, app/controllers/feedback/Survey.scala, frontend/sass/elements/_helpers.scss, test/controllers/FORSubmissionControllerSpec.scala
Changes based on feedback of performance tests and a few cleanups.
=> Tune performance

frontend/javascripts/radioToggle.js, frontend/javascripts/voaFor.js
no need for 2nd if statement it's doing the same thing
=> clean up js

app/controllers/Application.scala, app/views/inpageVacatedForm.scala.html, app/views/part0.scala.html, conf/messages, conf/messages.cy, test/controllers/PageZeroControllerSpec.scala
Re-work of the way the email flow is handled
=> FRV-1181 Part 2

conf/messages, conf/messages.cy
=> VOA-1248 Added changed text

app/views/part5.scala.html, conf/messages.cy
A couple of minor tweaks to display correct text
=> VOA-1246-1255 Fix errors to display correct values

app/views/part13.scala.html, conf/messages.cy
Testing showed a label not displaying the value. This PR is the fix.
=> VOA-1406 Fix label not displaying value

app/views/login.scala.html
This is to remove the image from the login.
=> VOA-1493 remove image from login page

Gruntfile.js
We are already in container. Not need for sandbox.
=> Disable chrome sandbox.

frontend/sass/application.scss, frontend/sass/custom/_form-block-labels.scss
from : github.com:alphagov/govuk_elements.git
=> Backport block-label.

app/ForFrontendModule.scala, app/config/wiring.scala, app/controllers/NotConnectedController.scala, app/controllers/PreviouslyConnectedController.scala, app/form/persistence/FormDocumentRepository.scala, app/form/persistence/MongoSessionRepository.scala, conf/application.conf, it/form/persistence/MongoSessionRepositorySpec.scala, project/FrontendBuild.scala, test/controllers/PreviouslyConnectedControllerSpec.scala
Remove dependency on save4Later microservice. Al session data are now stored to mongo.
=> Add MongoSessionRepository.

app/config/wiring.scala, app/controllers/AgentAPI.scala, app/controllers/FORSubmissionController.scala, app/controllers/NotConnectedController.scala, app/controllers/SaveForLater.scala, app/controllers/feedback/Survey.scala, app/form/Formats.scala, app/helpers/AddressAuditing.scala, app/models/Journey.scala, app/views/confirm.scala.html, app/views/confirmNotConnected.scala.html, app/views/inpageAfterSubmissionFeedbackForm.scala.html, project/FrontendBuild.scala, test/helpers/AddressAuditingSpec.scala
=> Add feedback survey after not connected journey.

LICENSE, build.sbt, project/plugins.sbt
- Fix unslate build
- Upgrade libraries
- Fix license
=> Fix unstable build

app/util/FieldElementsHelper.scala, app/views/helpers/fieldConstructor.scala.html, app/views/includes/summary/page6.scala.html, app/views/part6.scala.html, conf/messages, conf/messages.cy
Default play implementation always call toString on label element. Even if it’s already Html tree element.
=> Fix label rendering

app/views/helpers/summary/summaryBlock.scala.html, app/views/includes/summary/page0.scala.html, app/views/includes/summary/page1.scala.html, app/views/includes/summary/page10.scala.html, app/views/includes/summary/page11.scala.html, app/views/includes/summary/page12.scala.html, app/views/includes/summary/page13.scala.html, app/views/includes/summary/page14.scala.html, app/views/includes/summary/page2.scala.html, app/views/includes/summary/page3.scala.html, app/views/includes/summary/page4.scala.html, app/views/includes/summary/page5.scala.html, app/views/includes/summary/page6.scala.html, app/views/includes/summary/page7.scala.html, app/views/includes/summary/page8.scala.html, app/views/includes/summary/page9.scala.html, app/views/summary.scala.html
Full refactor of the check your answers page to use preferred dl list pattern. The content on many of the change links could be vastly improved, but that should be handled in another story/ticket.
=> Update check your answers page to use dl pattern instead of ul list

app/views/confirmVacated.scala.html, app/views/includes/surwayFeedback.scala.html, app/views/inpageAfterSubmissionFeedbackForm.scala.html, app/views/part10.scala.html, app/views/part11.scala.html, app/views/part12.scala.html, app/views/part14.scala.html, app/views/part3.scala.html, app/views/part6.scala.html
I have demoed this to Terry and Naveen
All tests pass
=> VOA-2036 Remove character count from all pages

app/controllers/PreviouslyConnectedController.scala, app/views/includes/account_info_header.scala.html, app/views/main2.scala.html, app/views/part1.scala.html, app/views/previouslyConnected.scala.html, conf/messages, conf/messages.cy, frontend/sass/custom/_form.scss
=> Revert "Revert "update the previously connected page""

app/controllers/Application.scala, app/views/helpers/summary/summaryBlock.scala.html, app/views/includes/summary/page1.scala.html, app/views/main2.scala.html, app/views/part2.scala.html, app/views/part3.scala.html, app/views/summary.scala.html
=> Migrate summary page to GDS

Gruntfile.js, app/views/confirm.scala.html, app/views/confirmNotConnected.scala.html, app/views/includes/formHelp.scala.html, app/views/includes/summary/page0.scala.html, app/views/includes/summary/page10.scala.html, app/views/includes/summary/page11.scala.html, app/views/includes/summary/page12.scala.html, app/views/includes/summary/page13.scala.html, app/views/includes/summary/page14.scala.html, app/views/includes/summary/page2.scala.html, app/views/includes/summary/page3.scala.html, app/views/includes/summary/page4.scala.html, app/views/includes/summary/page5.scala.html, app/views/includes/summary/page6.scala.html, app/views/includes/summary/page7.scala.html, app/views/includes/summary/page8.scala.html, app/views/includes/summary/page9.scala.html, app/views/includes/surveyFeedback.scala.html, frontend/javascripts/feedback.js, frontend/javascripts/voaFor.js, frontend/sass/application2.scss, frontend/sass/print_page_screen.scss
Add character count to feedback on confirm page
=> Voa 2461 Add character count to feedback on confirm page

conf/messages, conf/messages.cy
Changed hint text on radio buttons
=> Changes made for VOA-2321

app/form/PageSixForm.scala
Validation toDateIsAfterFromDate on the same level as amount field validation
=> VOA-2345 Improved validation in stepped rent

app/controllers/NotConnectedCheckYourAnswersController.scala, app/models/serviceContracts/submissions/NotConnectedSubmission.scala, build.sbt
Get selected language from request and set it in NotConnectedSubmission.lang
=> VOA-3239 RALD frontend: Get selected language from request 

app/controllers/LoginController.scala, app/security/LoginToHOD.scala, app/views/part1.scala.html, test/controllers/LoginControllerSpec.scala, test/security/LoginToHODSpec.scala, test/utils/MappingSpecs.scala
+ Fixed bug displaying address line 2 instead of line 3 on page 1
=> VOA-3277 RALD Capture property address in UserLogin audit

app/connectors/Audit.scala, app/controllers/ApplicationController.scala, app/controllers/FORSubmissionController.scala, app/controllers/LoginController.scala, app/controllers/dataCapturePages/ForDataCapturePage.scala, app/helpers/AddressAuditing.scala, app/models/Addresses.scala
- VOA-3277 RALD Capture original and updated property address in `FormSubmission` audit event
- VOA-3279 Capture RALD reference number in Splunk `manualAddressSubmitted` audit type
=> VOA-3277 FormSubmission audit, VOA-3279 manualAddressSubmitted

conf/messages, conf/messages.cy
changed the English message file as well to have consistency over the service
=> VOA-3317 - Added welsh translation to RALD Page 9

app/form/PageFourteenForm.scala, conf/messages, test/form/PageFourteenMappingSpec.scala
Also amended whitespace in messages file. Just waiting on the Welsh translation.
=> VOA-3312 - Added bespoke error messages for RALD Page 14

app/controllers/AgentAPI.scala, conf/messages, conf/messages.cy, it/aat/agentApi/POSTingSubmissionJson.scala
This reverts commit 095606f2165ba9fddd961f41d633a201be2ced5a.
=> Revert "VOA-3365 - Amended wording to reflect lockout time (#571)"

app/useCases/SaveInProgressSubmissionForLater.scala, build.sbt, test/useCases/SavingForLater.scala
by using `java.security.SecureRandom` in wrapper `scala.util.Random`
=> VOA-3371 Create secure password generation

app/views/part14.scala.html, build.sbt, project/plugins.sbt
Header "Any other factors" replaced by "Has anything else affected the rent?"
=> VOA-3492 RALD - update section 14 heading.

app/form/MappingSupport.scala, build.sbt, conf/application.conf, project/build.properties
```scala
val strictEmail = email.verifying("error.email", value => Try(new InternetAddress(value, true)).isSuccess)
```
=> VOA-3514 Investigate why some emails are rejected at submission
